name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load Docker environment variables
        run: |
          if [ -f .env ]; then export $(grep -v '^#' .env | xargs); fi

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: djag7/wisecow:latest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'

      - name: Deploy to Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo ${{ secrets.KUBECONFIG_BASE64 }} | base64 --decode > $HOME/.kube/config
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml
        env:
          KUBECONFIG: ~/.kube/config

    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Load environment variables
        run: |
          if [ -f $HOME/.env ]; then
            export $(grep -v '^#' $HOME/.env | xargs);
          fi

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'

      - name: Print KUBEConfig Base64 to verify (temporary)
        run: echo $KUBECONFIG_BASE64

      - name: Deploy to Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo $KUBECONFIG_BASE64 | base64 --decode > $HOME/.kube/config
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml
        env:
          KUBECONFIG: ~/.kube/config

