name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'

      - name: Deploy to Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > $HOME/.kube/config
          kubectl set image deployment/wisecow wisecow=djag7/wisecow:latest
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml
        env:
          KUBECONFIG: $HOME/.kube/config
